function [ ] = animation(Peak, Edge, robotCoordinates, TargetAll,...
                         x_center, y_center) 
% функция отрисовки статичных роботов и таргентных точек
% global MASHROB;

plotSurface(Peak, Edge, TargetAll); 

for i = 1:size(robotCoordinates,1)
    plot(robotCoordinates(i,1), ...
          robotCoordinates(i,2), ...
          'Marker','o',    ...
          'MarkerEdgeColor','m',...
          'MarkerSize', 5);
%           'MarkerFaceColor','m');
      
    text( robotCoordinates(i,1), ...
          robotCoordinates(i,2), ...  
          num2str(i));
    text(TargetAll(i,1),...
         TargetAll(i,2),...
         num2str(i));  
end

plot(x_center, y_center, '*r');